### ISSUE TITLE
Collect data

### ISSUE THREAD

**Issue by quargh** [quargh/capstone-project#1]
# Value Proposition
-Collect data from OSM
**As a author
**I want to be able to get json data of desired objects
**So that I will be able to project markers on a map.

# Description
Scribble / design or text

# Acceptance Criteria
 - [ ] Data should feature Germany / Europe

 ...
# Tasks
 - [ ] get data from osm
 - [ ] push data into mongo db
 - [ ] show the map
 - [ ] test call up data
 - [ ]  ...
# Complexity
L
