### ISSUE TITLE
Show Objects on map

### ISSUE THREAD

**Issue by quargh** [quargh/capstone-project#10]
# Value Proposition

- As a user
I want to be able to see objects on the map around me e.g. ev-Stations
So that I have an overview and can find the shortest way

# Description

![Image](https://user-images.githubusercontent.com/30600277/187658552-30a63854-b82f-4228-b705-c23d6cb35280.png)

# Acceptance Criteria
 - [x] Objects are shown on the map at their respective gps positions
 - [x] Objects are being clustered if high density on the map

# Tasks
 - [x] create a json file
 - [x] process json file and extract coordinates
 - [x] create markers for each coordinate
 - [x] implement clustering

# Complexity
L
