### ISSUE TITLE
get location interval

### ISSUE THREAD

**Issue by quargh** [quargh/capstone-project#11]
# Value Proposition

- As a user
I want my location to be automatically updated every x seconds
So that I can see my updated position without doing it manually e.g. when driving in a car

# Description

- Get location updates every x seconds

# Acceptance Criteria
 - [ ] Marker is moving on the map when user changes position
 - [ ] If GPS Button is active, marker of user location remains centered on the map, when user is moving => map will move on movement of user, in order to recenter the user location. 
 
# Tasks
 - [ ] set an interval of x seconds to get new geolocation 
 - [ ] stop auto-centering user when user drags or zooms the map and set GPS Button inactive
 - [ ] Test on mobile device and / or use mock location provider

# Complexity
M
