### ISSUE TITLE
Show distance

### ISSUE THREAD

**Issue by quargh** [quargh/capstone-project#13]
# Value Proposition

- As a user
I want to see if the charging station is within the range of my battery level
So that I do not run out of battery power on my way to it

# Description

- Get shortest distance to charging station

# Acceptance Criteria

 - [ ] Shortest distance is shown
 - [ ] A polyline on the map is showing route of shortest distance
 
# Tasks
 - [ ] load json with route via lat/lng values
 - [ ] show distance 
 - [ ] show polyline 

# Complexity
L
