### ISSUE TITLE
Create a container element - User Story 8

### ISSUE THREAD

**Issue by quargh** [quargh/capstone-project#2]
# Value Proposition

As a author
I want to be able to show content on different screen sizes
So that a user can use the app on any device

# Description

![Image](https://user-images.githubusercontent.com/30600277/184612526-3110f530-fbbf-4242-a748-3716423a83b7.png)

# Acceptance Criteria
- [ ] Create Basic container
- [ ] content must be centered horizinally
- [ ] content (map) must stretch
...
# Tasks
- [x] install mui
- [ ] addContainer
...
Complexity
xs

**Comment by RobertBReich** [comment]
Hey Stefan,

I think the "Create Basic container" should be in AC or Tasks, not in Value Proposition.
Not sure about those ... 

cheers
R.

**Comment by JessicaLoers** [comment]
**Hi @quargh**  👋

your App should be responsive anyway and this is not a feature of your App you have to write a user Story for.

When creating user stories, keep the following questions and suggestions in mind:

- What is the reason and the purpose of the feature? Focus on the user's need. 
- Don't switch the  User Story `Role` in the Value Proposition like e.g. (As a User / As anAuthor / As a Developer.... ) 
 **As a User**
 **I want to**  - describes the activity 
 **So that I**  - describes the desired value, purpose and benefit of User (in this case)
 
 **Description**
 - please be more precise 
 
** Acceptance Criteria** from the **Users perspective**
- Think about the different scenarios e.g.  possible user interactions, errors

**Task** is  **from Developers and for Developers** 
- a list of technical  to do's and explanations. 

I'm really sorry but I can't approve this user story. 😔

If you have any questions, feel free to ask me.
