### ISSUE TITLE
Include a Google map

### ISSUE THREAD

**Issue by quargh** [quargh/capstone-project#3]
# Value Proposition

As a developer
I want to integrate Google maps
So that I can build future features on it.

# Description

![Image](https://user-images.githubusercontent.com/30600277/185411090-7ecc68a1-adaf-4489-888a-f971448ae733.png)

# Acceptance Criteria
 - [x] Google map is included
 - [x] Google Logo must be visible

# Tasks
 - [x] get an API-Key
 - [x] Implement the Google map
 - [x] set Dimensions / padding of map
 - [x] show the map

# Complexity
L

**Comment by RobertBReich** [comment]
Hi Stefan,
I think "Include a Google map" should be in Acceptance Criteria.

cheers
R.

**Comment by quargh** [comment]
Hi Robert, ok i put "Google map is included" in Acceptance Criteria

**Comment by tsimvris** [comment]
Hi Stefan,

The scribble is missing

**Comment by quargh** [comment]
Hi @tsimvris , thank you I have updated my user story

**Comment by tsimvris** [comment]
Hi Stefan,

in your scribble is the Google Logo not visible and i cant see my location and marked locations around me.

**Comment by quargh** [comment]
Hi @tsimvris, ok i have updated my user story

**Comment by Gw3i** [comment]
Hello @quargh,
Good User Story!
I would change some things:
- Change the Value Proposition to a text, not a list item.
- Delete the '...' in Acceptance Criteria and Tasks
- I would mention that the user can see his position on the map and see the EV-Charging stations around him

**Comment by quargh** [comment]
Hi @Gw3i , ok i have updated my user story
