### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by quargh** [quargh/capstone-project#4]
# Value Proposition

- As a user
I want to be able to switch between day mode and night mode
So that I can read the screen in bright light (bright screen) / dark night  (does not blend) 

# Description
- Day Mode: bright colors / dark text
- Nightmode: dark colors / bright text

![nightmode](https://user-images.githubusercontent.com/30600277/185388095-d8b05949-efb5-4cb9-8450-897b0e1a4d84.png)

# Acceptance Criteria
 - [x] Switch Button to toggle between modes
 - [x] App must be visible in brightness
 - [x] App should not blend in darkness
 ...
# Tasks
 - [x] implement a switch button
 - [x] implement day / night themes
 - [x] create the corresponding map styles
 ...
# Complexity
L

**Comment by therealchrismcfly** [comment]
Hello Stefan 😃,

- I think you should add a scribble
- the switch button should be an acceptance criteria

Cheers,
Chris

**Comment by quargh** [comment]
Hello Chris @therealchrismcfly , ok I have updated description and acceptance criteria
