### ISSUE TITLE
Get Location access

### ISSUE THREAD

**Issue by quargh** [quargh/capstone-project#5]
# Value Proposition
As a user
I want to control the location access of an app
So that my privacy is preserved

# Description
Is invoked when user clicks the gps/crosshair icon:

![access_1](https://user-images.githubusercontent.com/30600277/186572335-9ab1e6a4-307b-4abb-a220-5fed0b1f60f9.png)

- ... in case the user granted location access:

![access_2](https://user-images.githubusercontent.com/30600277/186572482-8f5bc318-7579-4505-a56a-608ce678cec8.png)

- ... in case the user did not grant location access, but clicks the location icon anyway:

![access_3](https://user-images.githubusercontent.com/30600277/186572683-13fe543d-960a-48ae-9797-96d76221aec7.png)

# Acceptance Criteria
 - [x] User will be asked to grant location access and a marker will be set at his location if 'yes'
 - [ ] App will continue to work without user location if answered 'no'
 - [x] Location icon on the map is shown
 - [ ] In case user clicked 'no', an alert will be shown when user clicks location button

# Tasks
 - [x] let system ask user to grant location access
 - [x] center map and set a marker at users location if answered 'yes'
 - [x] create a location icon on the map to center the users location
 - [ ] In case user clicked 'no', show alert with explanation when user clicks location button anyway

# Complexity
L

**Comment by Mersag** [comment]
Hallo Stefan ,
Verstehe ich dich richtig? 
**Value** "Als Benutzer
 möchte ich den Standortzugriff einer App steuern
Damit meine Privatsphäre gewahrt bleibt"

Meine Frage hierzu = Was muss ich als Nutzer tun, dass dieses Fenster mit der Frage zum Standort erscheint oder nach welcher Aktion wird mir diese Frage gestellt?

Cooles Feature :-)

**Comment by quargh** [comment]
Hi Meral, 
ja genau die App kann aus Datenschutzgründen nicht auf den Standort des Benutzers zugreifen, ohne daß der User sich damit einverstanden erklärt hat. Super Frage, durch welche Aktion der Request ausgelöst wird. Das hatte ich mir noch nicht überlegt. Also 1.) wenn die App startet, und 2.) falls er nein gesagt hat und später dennoch seinen Standort haben will, indem er auf das Standort-Icon oben links klickt. Habe die Description entsprechend erweitert :-)

**Comment by Mersag** [comment]
HI Stefan ,
- 1.) Mega cool, wenn die App startet, wird der Nutzer gefragt. Love it :-)
- 2.) Wie wäre es, wenn du unter Acceptance Criteria, Standort -Icon für  spätere Standortänderung hinzufügst?
- 3.) Dem zu folge auch gleich einen Task für Standort -Icon.
Deine Description ist super. 
**Frage:**Ich nehme an, der Nutzer erkennt durch die Helligkeit des Icons, ob er Ja oder Nein angeklickt hat, bin ich da richtig? Wenn ja, was wäre das für eine Funktion (Task) und unter Acceptance Criteria würde ich dann sowas wie, Icon leuchtet bei Standort zusage.

**Comment by quargh** [comment]
Hi Meral, danke für dein Feedback :-)
Ok Punkte 2) und 3) habe ich gemacht...

Durch deine Frage habe ich überlegt und recherchiert und gesehen, daß mein Plan so nicht ganz funktioniert, weil dieser Standort Permission Request im Browser technisch nur genau 1 x ausgeführt werden kann. Das wusste ich vorher gar nicht. Im Sinne von "nein" bedeutet "nein". Sonst muß der User nämlich selbst in die Browser Einstellungen gehen und kann es erst dort wieder ändern.... Also kann ich den Request nur am Start der App durchführen. Zu deiner Frage, das Standort Icon oben links wäre immer da mit gleichbleibender Helligkeit. Und der User erkennt seine Auswahl daran, ob der blaue Marker gesetzt ist, sein Standort onClick auf Standort Icon auf der Map zentriert wird und das Standort Icon bekommt dann eine Füllung (siehe Scribble). Falls der User 'nein' gesagt hat und er klickt das Icon dennoch, würde ein Alert Fenster erscheinen mit dem Hinweis, daß die Einstellung manuell vorgenommen werden muß. Habe Description, Acceptance Criteria und Tasks entsprechend erweitert ;-)

**Comment by Mersag** [comment]
Guten Morgen Stefan, Großartig. Sieht Klasse aus.
